# COMMON APPLICATION PROPERTIES

# database init, supports mysql too
petclinic.database: hsqldb
spring:
  datasource:
    schema: classpath*:db/${petclinic.database}/schema.sql
    data: classpath*:db/${petclinic.database}/data.sql

# JPA
spring.jpa.hibernate.ddl-auto: none

# Internationalization
spring.messages.basename: messages/messages

# Actuator / Management
management.contextPath: /manage

# Logging
logging.level.org.springframework: INFO

server:
  port: 0
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048